import json

def convert_to_netscape(json_path, netscape_path):
    with open(json_path, 'r') as f:
        cookies = json.load(f)

    with open(netscape_path, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by a Python script\n")
        f.write("#\n")

        for cookie in cookies:
            domain = cookie.get('domain', '')
            flag = 'TRUE' if not cookie.get('hostOnly', False) else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            expiration = str(int(cookie.get('expirationDate', 0)))
            name = cookie.get('name', '')
            value = cookie.get('value', '')

            f.write("\t".join([domain, flag, path, secure, expiration, name, value]) + "\n")

# Ruta al archivo JSON de cookies y la ruta donde se guardará el archivo Netscape
json_path = 'C:\\Users\\Windows 11\\Desktop\\PYTHON FLASK WEBSITE\\descargador_videos\\cookies.json'  # Cambia esto a la ruta de tu archivo JSON
netscape_path = 'C:\\Users\\Windows 11\\Desktop\\PYTHON FLASK WEBSITE\\descargador_videos\\cookies_netscape.txt'  # Cambia esto a donde quieres guardar el archivo Netscape

convert_to_netscape(json_path, netscape_path)

